<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nKZWmD.' shared service.

return $this->privates['.service_locator.nKZWmD.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'paramFetcher' => ['privates', '.errored..service_locator.nKZWmD..FOS\\RestBundle\\Request\\ParamFetcher', NULL, 'Cannot autowire service ".service_locator.nKZWmD.": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.'],
    'user' => ['privates', '.errored..service_locator.nKZWmD..App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.nKZWmD.": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'paramFetcher' => 'FOS\\RestBundle\\Request\\ParamFetcher',
    'user' => 'App\\Entity\\User',
]);
