<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kdNeUqL' shared service.

return $this->privates['.service_locator.kdNeUqL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'droit' => ['privates', '.errored..service_locator.kdNeUqL.App\\Entity\\Droit', NULL, 'Cannot autowire service ".service_locator.kdNeUqL": it references class "App\\Entity\\Droit" but no such service exists.'],
    'paramFetcher' => ['privates', '.errored..service_locator.kdNeUqL.FOS\\RestBundle\\Request\\ParamFetcher', NULL, 'Cannot autowire service ".service_locator.kdNeUqL": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.'],
], [
    'droit' => 'App\\Entity\\Droit',
    'paramFetcher' => 'FOS\\RestBundle\\Request\\ParamFetcher',
]);
