<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhNpth1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhNpth1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVhNpth1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVhNpth1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVhNpth1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VhNpth1',
    'container.build_id' => '3f2bc628',
    'container.build_time' => 1572355145,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhNpth1');
