<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'auth_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/api/login']], [], []],
    'get_roles' => [[], ['_controller' => 'App\\Controller\\DroitController::getRoles'], [], [['text', '/api/roles']], [], []],
    'get_one_role' => [['id'], ['_controller' => 'App\\Controller\\DroitController::getRole'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/roles']], [], []],
    'add_role' => [[], ['_controller' => 'App\\Controller\\DroitController::add'], [], [['text', '/api/roles']], [], []],
    'update_role' => [['id'], ['_controller' => 'App\\Controller\\DroitController::update'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/roles']], [], []],
    'delete_role' => [['id'], ['_controller' => 'App\\Controller\\DroitController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/roles']], [], []],
    'add_users' => [[], ['_controller' => 'App\\Controller\\UserController::add'], [], [['text', '/api/users']], [], []],
    'get_one_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::getOneUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'get_all_user' => [[], ['_controller' => 'App\\Controller\\UserController::getAll'], [], [['text', '/api/users']], [], []],
    'is_active_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::activeUser'], [], [['text', '/activeOrDesactive'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'update_users' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], []],
];
